### ISSUE TITLE
Getting stuck at development mode

### ISSUE THREAD

**Issue by MarkosKon** [andrewbranch/gatsby-remark-vscode#115]
I can't complete the development build on an MDX blog that uses `gatsby-remark-vscode` after updating to Gatsby version 2.24.9. I am able to start the development server if I remove this plugin from the MDX `gatsbyRemarkPlugins` option, or if I downgrade Gatsby to 2.24.8.

I have a similar setup with @janosh blog. I was able to reproduce this issue by [cloning the repository](https://github.com/janosh/blog) and upgrading Gatsby to 2.24.9 version (on a Windows 10 machine). Maybe it's related to [this PR](https://github.com/gatsbyjs/gatsby/pull/25479)? 

Let me know If you can reproduce this issue, or if it's something else on my side.

**Comment by Enter-tainer** [comment]
Hi, I'm having the same issue. When I run `gatsby develop`, the program would get stuck.

**Comment by pwign** [comment]
Having the same issue here.

Stuck at `run page queries` step when using `gatsby develop`.

```
warn Query takes too long:
File path:
~/src/components/templates/blogTemplate.tsx
URL path: /blog/website-colors/
Context: {
    "id": "97b3b7f2-90bd-5d8e-94c6-8b4784cd0119"
warn Query takes too long:
File path: ~/src/pages/blog.tsx
URL path: /blog/
warn Query takes too long:
File path: ~/src/pages/index.tsx
URL path: /
```
Downgrading to Gatsby version to `2.24.8` resolved the issue.

**Comment by thedaviddias** [comment]
I confirm that I was having the same issue with the last version of Gatsby, downgrading to `2.24.8` solve indeed the issue but I would rather prefer to use a version updated of Gatsby 😢

**Comment by Enter-tainer** [comment]
Hi everyone, I've found a nice substitution [gatsby-remark-shiki](https://www.gatsbyjs.org/packages/gatsby-remark-shiki/). It also make use of vscode's textmate grammer. Here is a demo, using `vscode light+` theme.

![image](https://user-images.githubusercontent.com/25521218/89769518-d3b4aa80-db2f-11ea-80c5-8b52c30998fa.png)

**Comment by MarkosKon** [comment]
It seems that they fixed this. See the mentioned issue by vladar above this comment. 

I will close this issue for now but let me know if you still have problems.
