### ISSUE TITLE
Feature request: Title Header for the Script Name

### ISSUE THREAD

**Issue by garlen-javier** [andrewbranch/gatsby-remark-vscode#133]
It would be probably cool if we can show an optional title header for each code block similar on the image I attached.

![headetTitle](https://user-images.githubusercontent.com/71249192/104084369-6b562a80-5281-11eb-8588-b2cc6d4276ff.PNG)

**Comment by andrewbranch** [comment]
Thanks for the suggestion! I think that’s probably best done with another plugin like https://www.npmjs.com/package/@pastelsky/gatsby-remark-code-titles (make sure to run it _before_ gatsby-remark-vscode). I think plugins are best when they’re small and focused, so I don’t want this project to take on something that another plugin could do just as well.
