### ISSUE TITLE
Update for gatsby v3

### ISSUE THREAD

**Issue by codepunkt** [andrewbranch/gatsby-remark-vscode#144]
![image](https://user-images.githubusercontent.com/603683/110102935-a36f7a80-7da5-11eb-9ce0-cb6aebc6048d.png)

**Comment by zero-plusplus** [comment]
I am using machine translation.

To support gatsby v3, simply change the `peerDependencies` in package.json to `"^3.0.0"`.

https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#for-plugin-maintainers

**Comment by kremalicious** [comment]
There might be more updates required to make this plugin fully work with Gatsby v3. I am running into this issue locally, which makes local development a bit painful.

When running local dev server, after saving for the second or third time, the dev server just hangs with:

```
Missing onError handler for invocation 'building-schema', error was 'Error: Schema must contain
uniquely named types but contains multiple types named "GRVSCStylesheet".'. Stacktrace was 'Error:
 Schema must contain uniquely named types but contains multiple types named "GRVSCStylesheet".
```

This has also been reported over on gatsby repo https://github.com/gatsbyjs/gatsby/issues/30199

**Comment by andrewbranch** [comment]
Interesting find @kremalicious. I had observed earlier that multiple type declarations seemed to merge, which was really useful. I guess that’s not allowed anymore, which is a shame.

**Comment by kremalicious** [comment]
seems to have been addressed in upstream `gatsby` for all similar use cases, pending new Gatsby release https://github.com/gatsbyjs/gatsby/pull/30318

**Comment by andrewbranch** [comment]
Great! This is why I don’t fix bugs too fast 😂 

In seriousness, I’m not sure when I’ll have time to get to the rest of this issue, but if someone wants to open a PR updating the peer dep and making sure everything works, I will make the time to review it.

**Comment by tnorlund** [comment]
I just upgraded to Gatsby 3.0.1, and I'd like to install this package. When I attempt to, Get the error that the peer dependency is for Gatsby v 2.12.1. Is this still an issue?

**Comment by tnorlund** [comment]
I would really like to help out with this. I have a [PR](https://github.com/andrewbranch/gatsby-remark-vscode/pull/146), but I'm not sure how you are handling the Jest testing. The GraphQL queries are off. If I could get the testing working, I'm sure I could increment the packages required for Gatsby V3.

**Comment by tnorlund** [comment]
How do I NPM install this to my Gatsby site?

**Comment by andrewbranch** [comment]
Released as v3.2.1. Thanks @tnorlund!

**Comment by yehezkiell** [comment]
is this already fixed? could not use gatsby-remark-vscode with gatsby version 4.5.4 @andrewbranch

**Comment by andrewbranch** [comment]
#174
