### ISSUE TITLE
Code blocks in markdown lists

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#17]
Sorry for bothering you again so quickly but I believe I discovered an issue, a real one this time. :)

I have a [post with a bunch of code blocks in a markdown list](https://janosh.io/blog/disqus-comments#implementing-disqus) and `gatsby-remark-vscode` doesn't seem to pick up on them. This worked before with `gatsby-remark-prismjs` so maybe there's a problem in how `gatsby-remark-vscode` parses markdown? In this case, the markdown has the following structure:

    1. Step 1
    2. Step 2
     
        ```sh
       some code
       ```
    3. Step 3
    
       ```sh
       some more code
       ```

**Comment by andrewbranch** [comment]
Ah! I had assumed that `code` nodes had to be top-level. Should be fixed in v1.0.4. Thanks again!

**Comment by janosh** [comment]
Again fix confirmed. Thanks a lot!
