### ISSUE TITLE
How to use the GitHub VSCode theme

### ISSUE THREAD

**Issue by ghoshnirmalya** [andrewbranch/gatsby-remark-vscode#171]
I would like to use the [GitHub Dark Default](https://github.com/primer/github-vscode-theme/blob/master/package.json#L40-L44) theme. However, if I use it like the following:

```js
{
  theme: "GitHub Dark Default",
  extensions: ["github-vscode-theme"],
},
```

I get the following error:

```bash
..

errno: -2,
syscall: 'open',
path: '/Users/username/project_name/node_modules/github-vscode-theme/themes/light-default.json',

..
```

If I use the following:

```js
{
  theme: "GitHub Dark Default",
  extensions: [
    "./node_modules/github-vscode-theme/themes/dark-default.json",
  ],
}
```

I get the following error:

```bash
Error: Invalid option 'extensions': Extension paths must be absolute. Received './node_modules/github-vscode-theme/themes/dark-default.json'.
```

Is there a way in which I can use the GitHub default dark theme?

**Comment by andrewbranch** [comment]
It looks like that repo generates their theme files with a build step, so installing it straight from GitHub won’t work. You’d have to build yourself a local copy, or ask them to publish a built version as a package somewhere. Sorry, some theme repos just aren’t easy to work with 😕

**Comment by ghoshnirmalya** [comment]
No problem. Thank you for your reply.
