### ISSUE TITLE
Clash with gatsby-remark-code-titles

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#19]
I just realized there's a little more to #17. I'm using [`gatsby-remark-code-titles`](https://www.gatsbyjs.org/packages/gatsby-remark-code-titles) which prepends a `div.gatsby-code-title` to code fences with a `title` option.

If I include `gatsby-remark-vscode` before `gatsby-remark-code-titles` in `gatsby-config.js` all the titles disappear, presumably because `gatsby-remark-vscode` prunes all code fence options. I think it would be good to mention in the readme that `gatsby-remark-vscode` should be loaded _after_ all other plugins that rely on code fence options.
If I include `gatsby-remark-code-titles` first, then all titles reappear. However, for code fences in markdown lists, the titles are ill-placed (way above their corresponding fence) as seen here:

---
![Screenshot 2019-05-07 at 09 08 48](https://user-images.githubusercontent.com/30958850/57283913-13c4ec00-70a8-11e9-8c10-e69b5be9909c.png)
---

There may be more `gatsby-remark` plugins that rely on code fence options not to be stripped but the HTML for that fence to already be in place. Would there be a problem with leaving the options in place?

Also, do you think `gatsby-remark-vscode` might support adding markup around code fences based on options or is that outside its scope?

**Comment by andrewbranch** [comment]
How did this work with the Prism plugin?

> There may be more gatsby-remark plugins that rely on code fence options not to be stripped but the HTML for that fence to already be in place. Would there be a problem with leaving the options in place?

I'm not sure I understand this—gatsby-remark-vscode isn't just removing your options, it's replacing the entire code fence with HTML, and that’s what gatsby-remark-prismjs does too. I might add something to the README to make sure people know that after this plugin, you no longer _have_ a code fence, but gatsby-remark-code-titles already has a specific warning for this:

```js
// IMPORTANT: this must be ahead of other plugins that use code blocks
```

I'm not sure why the titles are floating way up there, but it must be a subtle CSS difference. It should be relatively easy to fiddle with the style inspector and compare with the prismjs version and see what the difference is. Let me know if it ends up being something that seems like gatsby-remark-vscode should handle by default.

> Also, do you think gatsby-remark-vscode might support adding markup around code fences based on options or is that outside its scope?

Absolutely. I considered building customizable renderers into the first release, but I decided to wait and see if there was any interest. The other thing I'm considering, which would allow me to use this plugin on my own blog, is exposing the tokenization information to GraphQL, which would allow you to consume code block tokens as data and build a completely custom React UI for them. It sounds like that would be overkill for your needs at this point, but it would prevent an ever-growing set of plugin options by giving you an escape hatch to customize literally anything.

So, action items: can you either

1. Figure out what the CSS problem with those titles are, or
2. Send me a test deployment link with the problem?

Thanks for sticking with this plugin; it's super helpful to see how it works in the wild!

**Comment by janosh** [comment]
> I'm not sure why the titles are floating way up there, but it must be a subtle CSS difference.

I don't think it's a CSS problem. If you check those titles in the inspector, they're actually out-of-place _in the markup_, i.e. placed way above their corresponding code blocks. For some reason, `gatsby-remark-code-titles` seems to fail to find the correct place at which to insert its title `div` for a given code block only if that code block is indented, i.e. is part of a list in this case. No idea why it worked fine with `gatsby-remark-prisms`. I'll look into that.

> Absolutely. I considered building customizable renderers into the first release, but I decided to wait and see if there was any interest.

That sounds great! Now I'm already looking forward to the next version of `gatsby-remark-vscode`. :)
No pressure though.

> The other thing I'm considering, which would allow me to use this plugin on my own blog, is exposing the tokenization information to GraphQL, which would allow you to consume code block tokens as data and build a completely custom React UI for them.

That would be next level! Sounds like just the thing to show off the power of all the modern web technologies bundled into Gatsby too! It would go beyond what I'd expect this plugin to do, though. If you intend to take `gatsby-remark-vscode` that far, it might be worth it to give it a fancy name that doesn't link it so tightly to VS Code.

> Thanks for sticking with this plugin; it's super helpful to see how it works in the wild!

Well of course! This plugin is already amazing and has a huge potential! I'm thinking there should a blog post on it on the Gatsby website so more people hear of it.

**Comment by andrewbranch** [comment]
This is a bug with gatsby-remark-code-titles:

https://github.com/DSchau/gatsby-remark-code-titles/blob/010c220df2edbd15ba0f29d7d908ec06ee49a6bb/src/index.js#L37

It's inserting the new node in `markdownAST.children` (the top level) even though the code fence node might not be at the top level. The intention was to splice the new node into the code node's parent.

The callback to `visit` is passed a third parameter, the node's parent. Add that in and swap `markdownAST` on line 37 with that, and it should work.

**Comment by janosh** [comment]
Yeah, just realized this myself after checking my site a few weeks ago and noticing that _actually_ it hadn't worked back then with PrismJs either. I just never noticed. :)
Thanks for looking into this!

**Comment by janosh** [comment]
FYI [people are noticing](http://disq.us/p/21rkc4a) the excellent results `gatsby-remark-vscode` gives. :)

**Comment by andrewbranch** [comment]
So cool! 😄
