### ISSUE TITLE
copy text from code block

### ISSUE THREAD

**Issue by ar-stackrox** [andrewbranch/gatsby-remark-vscode#20]
Thanks for the awesome work @andrewbranch !

Do you know If there is any way to pair this with a plugin to let the user copy the text from a code block?

**Comment by janosh** [comment]
@andrewbranch I'm guessing this functionality might eventually become part of `gatsby-remark-vscode`?

@andrewbranch Until then you might want to look at [gatsby#5030](https://github.com/gatsbyjs/gatsby/issues/5030) or [`gatsby-remark-code-buttons`](https://github.com/iamskok/gatsby-remark-code-buttons).

**Comment by ar-stackrox** [comment]
oooh thanks! i'll check this out

**Comment by smockle** [comment]
> I'm guessing this functionality might eventually become part of `gatsby-remark-vscode`?

Is there an aspect of copying which could be improved using the information generated by `gatsby-remark-vscode`? Personally, I consider copy buttons outside the scope of a syntax highlighting plugin.

The Gatsby plugin docs don’t explicitly endorse the Unix philosophy, but it seems better to resolve any compatibility issues with`gatsby-remark-code-buttons` than to reimplement its functionality.

**Comment by janosh** [comment]
@smockle As @andrewbranch [indicated here](https://github.com/andrewbranch/gatsby-remark-vscode/issues/19#issuecomment-491531474), `gatsby-remark-vscode` might not remain a plugin purely concerned with syntax highlighting in the long term.

**Comment by andrewbranch** [comment]
`gatsby-remark-vscode` will certainly remain solely focused on syntax highlighting, but the ways in which it exposes syntax-related information might grow, such that someone could use it to compose syntax highlighting with other UI bits in a completely custom way.

To answer the original question: theoretically this plugin should not conflict with another plugin that adds a copy button, as long as the other plugin runs first, and leaves the `code` node of the markdown AST intact. A quick glance at gatsby-remark-code-buttons _looks_ like it should work, but it will only work if it runs _first_: once this plugin runs, the `code` node is transformed into an `html` node, and any other plugins down the chain will have no idea that this was ever a code block.

**Comment by janosh** [comment]
Ah, thanks for the clarification.
