### ISSUE TITLE
Horizontal scrolling even when blocks fit their container

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#21]
Using `gatsby-remark-vscode` with its default configuration, I get a little bit of horizontal scrolling in code blocks even when their content fits within the `<pre>` container as can be seen e.g. on [this page](https://janosh.io/blog/google-maps+react-hooks). Passing the option `injectStyles: false` removes this horizontal scrolling but also some padding that I'd like to keep. Is this scrolling behavior intentional?

**Comment by andrewbranch** [comment]
Nope, not intentional! I'm guessing the sites I was testing on had a CSS reset that included `* { box-sizing: border-box; }`. Fixed in v1.0.5, deploying now. Thanks!

**Comment by andrewbranch** [comment]
Reopening to track the fact that Actions appear to be busted, which means v1.0.5 isn't published: https://twitter.com/atcb/status/1135330635310985216

**Comment by andrewbranch** [comment]
Published.

**Comment by janosh** [comment]
Excellent, thanks for the lightning-fast fix.

Fyi, it says ["Unable to find a readme for gatsby-remark-vscode@1.0.5"](https://www.npmjs.com/package/gatsby-remark-vscode) on NPM.

**Comment by andrewbranch** [comment]
Maybe npm was having issues? It looks fine to me now.
