### ISSUE TITLE
Dependence on oniguruma causes node 12 incompatibility

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#22]
I updated to node v12 and now `yarn install` fails with the following error message
```sh
error ./node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Output:
gyp info using node-gyp@3.8.0
gyp info using node@12.3.1 | darwin | x64
```
Checking `yarn-lock` shows that this is a `gatsby-remark-vscode` dependence. There's a [PR to add node 12 support](https://github.com/atom/node-oniguruma/pull/93) to `oniguruma`.

**Comment by andrewbranch** [comment]
Excellent, I noticed this a while back but that PR wasn't up yet. Just subscribed to it.

**Comment by janosh** [comment]
The fix was just merged and published as [7.2.0](https://www.npmjs.com/package/oniguruma).

**Comment by andrewbranch** [comment]
I saw. It's on my to-do list for tonight 😄 

If you're in a hurry, I'll merge a PR now if you send one over.

**Comment by janosh** [comment]
Not exactly in a hurry but here's #23 anyway. :)
