### ISSUE TITLE
Support for comment directives?

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#27]
Are there any plans to add support for comment directives (`// highlight-line`)? They are in quite popular use and make highlights in code blocks much easier to maintain if the code (and hence the line numbers) change over time.

**Comment by andrewbranch** [comment]
Sure, why not? I don’t personally love how magic that syntax is, but I don’t really have a better idea for something resilient to line number changes. And as an underdog to Prism by orders of magnitude, it’s probably good to be as compatible as possible.

I’d like to do this by introducing the concept of _line transformers_, which are functions that take information about a line and return new string content and HTML attributes for the line. Pseudocode:

```ts
interface LineTransformerArguments {
  lineText: string;
  language?: string;
  codeBlockOptions?: object;
  attrs: HTMLAttributes;
}

interface LineTransformer {
  (args: LineTransformerArgs): {
    lineText: string;
    attrs: HTMLAttributes;
  };
}

interface HighlightCommentDirectiveTransformerOptions {
  commentText?: string;
}

function createHighlightCommentDirectiveTransformer({
  commentText = 'highlight-line',
}: HighlightCommentDirectiveTransformerOptions = {}): LineTransformer {
  return function transform({
    lineText,
    language,
    attrs,
  }) {
    if (lineText.endsWith(getCommentForLanguage(language, commentText)) {
      return {
        lineText: lineText.replace(/* ... */, ''),
        attrs: addClassName(attrs, highlightClassName),
      };
    }
    return { lineText, attrs };
  };
)
```

I’m fine with including that one as a default. You could add/remove/override transformers in gatsby-config:

```js
const createHighlightCommentDirectiveLineTransformer = require('gatsby-remark-vscode/transformers/highlight-comment-directive');
const myCoolTransformer = require('../my-cool-transformer');

// ...
options: {
  lineTransformers: [
    createHighlightCommentDirectiveLineTransformer(),
    myCoolTransformer,
  ],
}
```

**Comment by janosh** [comment]
Line transformers sounds like a good and flexible approach! I don't quite grasp the scope of your pseudocode though. Would a line-transformer be able to affect the lines around it? I'm asking because [being compatible with Prism](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#line-highlighting) would include things like `// highlight-next-line` and `// highlight-start` which highlights every line until encountering `// highlight-end`.

**Comment by andrewbranch** [comment]
Great point. I think a line transformer can only change one line at a time, but it should be able to get the contents of other lines. I think that would neatly enable ranges and such.

**Comment by janosh** [comment]
Let me know if I can help with this one.

**Comment by andrewbranch** [comment]
@janosh that would be awesome! I’ll try to post a more fleshed-out idea about an API that would enable `// highlight-next-line` and friends tonight. Thank you!

**Comment by andrewbranch** [comment]
Ok, so I think the idea I originally posted is mostly the right abstraction, but I would add a generic `state` property that gets passed to each subsequent line transformer call from the previous, and I would allow returning an `undefined` line to signify dropping the line:

```ts
interface LineTransformerResult<T> {
  line?: {
    text: string;
    attrs: HTMLAttributes;
  };
  state: T | undefined;
}

interface LineTransformerArgs<T> extends LineTransformerResult<T> {
  language: string;
  codeBlockOptions: object;
}

type LineTransformer<T = any> = (args: LineTransformerArgs<T>) => LineTransformerResult<T> | undefined;
```

So when you return a `state` property in the object, it gets passed to the next call. This way, when you see a line like `// highlight-start`, you could set state to `true`, then back to `false` or `undefined` once you see a line like `// highlight-end`:

```ts
type HighlightCommentTransfomerState = {
  inHighlightRange?: boolean;
  highlightNextLine?: boolean;
};

function createHighlightCommentDirectiveTransformer(): LineTransformer<HightlightCommentTransfomerState> {
  return ({ text, attrs, state }) => {
    if (line.endsWith('// highlight-start')) {
      return { state: { inHighlightRange: true } }; // no `line` - drop this line from output
    }
    if (line.endsWith('// highlight-end')) {
      return { state: { inHighlightRange: false } }; // again no `line`
    }
    if (line.endsWith('// highlight-next-line')) {
      return { state: { highlightNextLine: true } }; // again no `line`
    }
    if (line.endsWith('// highlight-line') || state && state.inHighlightRange) {
      // return attrs with added class name, text with comment removed, current state
    }
    if (state && state.highlightNextLine) {
      // return attrs with added class name, empty state, unchanged text
    }
    return { text, attrs, state }; // default: don’t change anything, propagate state to next call
  };
}
```

Line transfomers could be introduced into the system by a new plugin option `lineTransformers: LineTransformer[]`, which would include a default set that includes a transformer specifically for line-highlighting comment directives. However, I’d like to keep this a “private API” for a time, as I think the same system could be used to implement #28, and I want to feel free to adjust it as necessary to ensure that whatever we come up with is flexible enough to implement both this feature and #28.

Implementation-wise, there will probably be changes around here: https://github.com/andrewbranch/gatsby-remark-vscode/blob/0972ff25726b6eee6b587dd5df1fd8460e6d0777/src/index.js#L254

The text and html attributes for each line will need to be piped through each line transformer in sequence. Note though that the `state` for each line transformer should be isolated from the other transformers. Could look something like:

```ts
const prevTransformerStates = [];
for (let lineIndex = 0; lineIndex < rawLines.length; lineIndex++) {
  let line = rawLines[lineIndex];
  let attrs = {};
  for (let i = 0; i < lineTransformers.length; i++) {
    const transformer = lineTransformers[i];
    const state = prevTransformerStates[i];
    const txResult = transformer({ state, line: { text: line, attrs }, codeBlockOptions, language });
    attrs = txResult.attrs;
    line = txResult.line;
    prevTransformerStates[i] = txResult.state;
  }
}
```

Hopefully this gives you a fairly clear idea of what I’m thinking without being overly prescriptive—treat my code examples as illustration, not mandate. What do you think?

**Comment by janosh** [comment]
Looks great! I have to prepare for an oral exam on Monday but I'll try and tackle this later next week!

**Comment by janosh** [comment]
Sorry, I completely forgot about the PR I promised. Looking into it now.

I have a few questions:
- I'm not very familiar with TypeScript yet. Where is `HTMLAtrributes` coming from? Do you mean [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d948328df314ccf7b854f9e593c570cc9f6c7cbd/types/react/index.d.ts#L1628)?
- Do you have a mapping from language id to the language's way of commenting, i.e. how to implement `getCommentForLanguage`.
- Should `highlightClassName` be made a plugin option? It seems like the current class name for line highlights [is hardcoded](https://github.com/andrewbranch/gatsby-remark-vscode/blob/14f6f367ff89b585597112045819c50fa33a1ea4/src/index.js#L280) as `'vscode-highlight-line-highlighted'`.
- Does `addClassName(attrs, highlightClassName)` just take the porperty `attrs.className` and call `joinClassNames(attrs.className, highlightClassName)`?

I'll put together a very rudimentary PR even though this is far from complete just so we can start discussing actual changes.

**Comment by andrewbranch** [comment]
Whoa, awesome! Let me take a look. Answers:

> I'm not very familiar with TypeScript yet. Where is HTMLAtrributes coming from? Do you mean this?

Indeed I mentally conflated React.HTMLAttributes with the regular `HTMLElement` type, which contains both attribute-like properties and other properties/methods. This library is written in JS with some TS-supporting JSDoc, so if the types aren’t convenient, it’s best to ignore them. I wrote it this way to help prove to myself how it would work, and that it could be well-typed.

> Do you have a mapping from language id to the language's way of commenting, i.e. how to implement getCommentForLanguage.

Nope! Didn’t think of it until now 😱. I mean, it doesn’t actually _have_ to match the language’s comment format. What does gatsby-remark-prismjs do? I suspect they may just support `//` across the board.

> Should highlightClassName be made a plugin option? It seems like the current class name for line highlights is hardcoded as 'vscode-highlight-line-highlighted'.

That’s so people can use this [static CSS](https://github.com/andrewbranch/gatsby-remark-vscode/blob/14f6f367ff89b585597112045819c50fa33a1ea4/styles.css#L32) if they want. I think if we revisit that I’d like to do it separately.

> Does addClassName(attrs, highlightClassName) just take the porperty attrs.className and call joinClassNames(attrs.className, highlightClassName)?

Yeah, that’s probably what I had in mind. I wrote it that way in my example because I figured it was not the most relevant/interesting part of what I was trying to demonstrate.

**Comment by janosh** [comment]
> Nope! Didn’t think of it until now 😱. I mean, it doesn’t actually have to match the language’s comment format. What does gatsby-remark-prismjs do? I suspect they may just support // across the board.

That's correct, I think. I'd looked for some examples of code blocks with comment directives in other languages but couldn't find any without looking too hard. So I also presumed they just use `// ` for all languages.

I actually thought being language specific would be better here as that would allow writers to copy & paste code snippets from markdown files into actual projects without having to remove or comment out highlight directives. It's not that unusual for me to copy code from markdown back into working files, perform some tests and make some changes before pasting back into markdown. With language specific comment directives that would be seamless. That's why I kept `getCommentForLanguage` for the time being but if the main goal for now is doing everything like `gatsby-remark-prismjs` then we can simplify things a bit.

**Comment by andrewbranch** [comment]
I wouldn’t be against an approach like

- hard-code a map for every language supported out of the box
- allow an option to be passed in to merge with that map
- fall back to `//` if we don’t have an entry for the source language.

**Comment by janosh** [comment]
Sounds good. In that case we should still check for `// ` in the different `if endsWith` checks in `createHighlightDirectiveLineTransformer` regardless of language to retain compatibility with `gatsby-remark-prismjs`.

**Comment by janosh** [comment]
Which languages do we want to support out of the box? [Here are all the ones](https://github.com/microsoft/vscode-markdown-tm-grammar/blob/master/build.js#L8) supported by `vscode-markdown-tm-grammar`. Should we try to go for that or discard some?

```js
const languages = [
	{ name: 'css', language: 'css', identifiers: ['css', 'css.erb'], source: 'source.css' },
	{ name: 'basic', language: 'html', identifiers: ['html', 'htm', 'shtml', 'xhtml', 'inc', 'tmpl', 'tpl'], source: 'text.html.basic' },
	{ name: 'ini', language: 'ini', identifiers: ['ini', 'conf'], source: 'source.ini' },
	{ name: 'java', language: 'java', identifiers: ['java', 'bsh'], source: 'source.java' },
	{ name: 'lua', language: 'lua', identifiers: ['lua'], source: 'source.lua' },
	{ name: 'makefile', language: 'makefile', identifiers: ['Makefile', 'makefile', 'GNUmakefile', 'OCamlMakefile'], source: 'source.makefile' },
	{ name: 'perl', language: 'perl', identifiers: ['perl', 'pl', 'pm', 'pod', 't', 'PL', 'psgi', 'vcl'], source: 'source.perl' },
	{ name: 'r', language: 'r', identifiers: ['R', 'r', 's', 'S', 'Rprofile', '\\{\\.r.+?\\}'], source: 'source.r' },
	{ name: 'ruby', language: 'ruby', identifiers: ['ruby', 'rb', 'rbx', 'rjs', 'Rakefile', 'rake', 'cgi', 'fcgi', 'gemspec', 'irbrc', 'Capfile', 'ru', 'prawn', 'Cheffile', 'Gemfile', 'Guardfile', 'Hobofile', 'Vagrantfile', 'Appraisals', 'Rantfile', 'Berksfile', 'Berksfile.lock', 'Thorfile', 'Puppetfile'], source: 'source.ruby' },
	// 	Left to its own devices, the PHP grammar will match HTML as a combination of operators
	// and constants. Therefore, HTML must take precedence over PHP in order to get proper
	// syntax highlighting.
	{ name: 'php', language: 'php', identifiers: ['php', 'php3', 'php4', 'php5', 'phpt', 'phtml', 'aw', 'ctp'], source: ['text.html.basic', 'source.php'] },
	{ name: 'sql', language: 'sql', identifiers: ['sql', 'ddl', 'dml'], source: 'source.sql' },
	{ name: 'vs_net', language: 'vs_net', identifiers: ['vb'], source: 'source.asp.vb.net' },
	{ name: 'xml', language: 'xml', identifiers: ['xml', 'xsd', 'tld', 'jsp', 'pt', 'cpt', 'dtml', 'rss', 'opml'], source: 'text.xml' },
	{ name: 'xsl', language: 'xsl', identifiers: ['xsl', 'xslt'], source: 'text.xml.xsl' },
	{ name: 'yaml', language: 'yaml', identifiers: ['yaml', 'yml'], source: 'source.yaml' },
	{ name: 'dosbatch', language: 'dosbatch', identifiers: ['bat', 'batch'], source: 'source.batchfile' },
	{ name: 'clojure', language: 'clojure', identifiers: ['clj', 'cljs', 'clojure'], source: 'source.clojure' },
	{ name: 'coffee', language: 'coffee', identifiers: ['coffee', 'Cakefile', 'coffee.erb'], source: 'source.coffee' },
	{ name: 'c', language: 'c', identifiers: ['c', 'h'], source: 'source.c' },
	{ name: 'cpp', language: 'cpp', identifiers: ['cpp', 'c\\+\\+', 'cxx'], source: 'source.cpp', additionalContentName: ['source.cpp'] },
	{ name: 'diff', language: 'diff', identifiers: ['patch', 'diff', 'rej'], source: 'source.diff' },
	{ name: 'dockerfile', language: 'dockerfile', identifiers: ['dockerfile', 'Dockerfile'], source: 'source.dockerfile' },
	{ name: 'git_commit', identifiers: ['COMMIT_EDITMSG', 'MERGE_MSG'], source: 'text.git-commit' },
	{ name: 'git_rebase', identifiers: ['git-rebase-todo'], source: 'text.git-rebase' },
	{ name: 'go', language: 'go', identifiers: ['go', 'golang'], source: 'source.go' },
	{ name: 'groovy', language: 'groovy', identifiers: ['groovy', 'gvy'], source: 'source.groovy' },
	{ name: 'pug', language: 'pug', identifiers: ['jade', 'pug'], source: 'text.pug' },

	{ name: 'js', language: 'javascript', identifiers: ['js', 'jsx', 'javascript', 'es6', 'mjs', '\\{\\.js.+?\\}'], source: 'source.js' },
	{ name: 'js_regexp', identifiers: ['regexp'], source: 'source.js.regexp' },
	{ name: 'json', language: 'json', identifiers: ['json', 'json5', 'sublime-settings', 'sublime-menu', 'sublime-keymap', 'sublime-mousemap', 'sublime-theme', 'sublime-build', 'sublime-project', 'sublime-completions'], source: 'source.json' },
	{ name: 'jsonc', language: 'jsonc', identifiers: ['jsonc'], source: 'source.json.comments' },
	{ name: 'less', language: 'less', identifiers: ['less'], source: 'source.css.less' },
	{ name: 'objc', language: 'objc', identifiers: ['objectivec', 'objective-c', 'mm', 'objc', 'obj-c', 'm', 'h'], source: 'source.objc' },
	{ name: 'swift', language: 'swift', identifiers: ['swift'], source: 'source.swift' },
	{ name: 'scss', language: 'scss', identifiers: ['scss'], source: 'source.css.scss' },

	{ name: 'perl6', language: 'perl6', identifiers: ['perl6', 'p6', 'pl6', 'pm6', 'nqp'], source: 'source.perl.6' },
	{ name: 'powershell', language: 'powershell', identifiers: ['powershell', 'ps1', 'psm1', 'psd1'], source: 'source.powershell' },
	{ name: 'python', language: 'python', identifiers: ['python', 'py', 'py3', 'rpy', 'pyw', 'cpy', 'SConstruct', 'Sconstruct', 'sconstruct', 'SConscript', 'gyp', 'gypi', '\\{\\.python.+?\\}'], source: 'source.python' },
	{ name: 'regexp_python', identifiers: ['re'], source: 'source.regexp.python' },
	{ name: 'rust', language: 'rust', identifiers: ['rust', 'rs', '\\{\\.rust.+?\\}'], source: 'source.rust' },
	{ name: 'scala', language: 'scala', identifiers: ['scala', 'sbt'], source: 'source.scala' },
	{ name: 'shell', language: 'shellscript', identifiers: ['shell', 'sh', 'bash', 'zsh', 'bashrc', 'bash_profile', 'bash_login', 'profile', 'bash_logout', '.textmate_init', '\\{\\.bash.+?\\}'], source: 'source.shell' },
	{ name: 'ts', language: 'typescript', identifiers: ['typescript', 'ts'], source: 'source.ts' },
	{ name: 'tsx', language: 'typescriptreact', identifiers: ['tsx'], source: 'source.tsx' },
	{ name: 'csharp', language: 'csharp', identifiers: ['cs', 'csharp', 'c#'], source: 'source.cs' },
	{ name: 'fsharp', language: 'fsharp', identifiers: ['fs', 'fsharp', 'f#'], source: 'source.fsharp' },
	{ name: 'dart', language: 'dart', identifiers: ['dart'], source: 'source.dart' },
	{ name: 'handlebars', language: 'handlebars', identifiers: ['handlebars', 'hbs'], source: 'text.html.handlebars' },
	{ name: 'markdown', language: 'markdown', identifiers: ['markdown', 'md'], source: 'text.html.markdown' },
	{ name: 'log', language: 'log', identifiers: ['log'], source: 'text.log' }
];
```

**Comment by andrewbranch** [comment]
Everything that’s in `lib/grammars` after a build. I also list them in the README. I assume this list is the same. I’d be fine if we also just start with the most popular ones and/or ones we know off the top of our heads 😄

**Comment by janosh** [comment]
I have to tell you I'm so happy this plugin exists. The ability to extend the built-in syntax highlighting (which is already awesome) by installing arbitrary VS Code extensions is flat-out amazing! Thanks so much for working on this! 👍

**Comment by johnletey** [comment]
I have to second what @janosh just said! I found this plugin a while ago, and finally decided to set it up with the [Gatsby Starter Blog](https://gatsby-starter-blog-demo.netlify.com) today.

Works like a charm 🎉! And no hassle with set up either!

This is just amazing @andrewbranch! Well done!

Planning on contributing in the near future, so keep your eyes out for some PRs 👀 😄

**Comment by andrewbranch** [comment]
That’s so nice to hear! 😊 @janosh kind of inspired me to put some more investment into this plugin, and now it’s on its way to exposing its guts to GraphQL so people can build their own fully customizable React-based renderers: https://github.com/andrewbranch/gatsby-remark-vscode/tree/graphql

Looking forward to seeing your future contributions, @johnletey 😄
