### ISSUE TITLE
Load extensions that change existing grammars?

### ISSUE THREAD

**Issue by codepunkt** [andrewbranch/gatsby-remark-vscode#29]
Some extensions seem to change exising grammars, for example [`jpoissonnier.vscode-styled-components`](https://github.com/styled-components/vscode-styled-components).

Is there a way to enable these?

**Comment by andrewbranch** [comment]
I think so? I’m not sure if you’re just asking or if you’re telling me it’s not working 😅

**Comment by codepunkt** [comment]
It's not working 😄

**Comment by andrewbranch** [comment]
Can you describe what you tried, or link me to a repo?

**Comment by codepunkt** [comment]
Of course. I tried to add `jpoissonnier.vscode-styled-components` in order to get better styled-component css syntax highlighting embedded into jsx code.

Repo is here:
https://github.com/codepunkt/codepunkt.de

1. Clone, yarn install, yarn start
2. Open browser, click "view all articles", click "view article", see example code using your plugin and a screenshot of what it looks like in vscode right up top.

**Comment by andrewbranch** [comment]
Shipped in 1.1.0 (#33)
