### ISSUE TITLE
Visual Studio Marketplace rate limiting

### ISSUE THREAD

**Issue by codepunkt** [andrewbranch/gatsby-remark-vscode#30]
When downloading extensions from visual studio marketplace, rate limiting can kick in for anonymous requests like the one made in this plugin.

As a company with hundreds of developers downloading lots plugins, extensions and more for both Visual Studio and Visual Studio Code, running a gatsby build in our CI regularly breaks because the request made [here](https://github.com/andrewbranch/gatsby-remark-vscode/blob/master/src/downloadExtension.js#L56) returns with a 429 because the rate limit for anonymous requests from our IP is reached.

I have a few ideas how we could work around this (in the scope of this plugin), but i'd love to hear yours. What would you suggest?

**Comment by andrewbranch** [comment]
Ah, interesting. One thing you could do would be to check the plugin contents (or the important parts of it) into source control and resolve to that. Currently, the plugin caches downloaded extensions inside node_modules (where it’s almost guaranteed to be gitignored). I can definitely see an option where it downloads to a folder you specify so that you could check that folder in. (To clarify, I would copy only the files we actually need out of the plugin contents.) What were you thinking of?

**Comment by codepunkt** [comment]
Either that (easier) or some way of passing authentication for visual studio marketplace to the plugin (probably way harder, no clue how auth works there).

**Comment by andrewbranch** [comment]
That’s an interesting thought but probably doesn’t help you in CI though, right?

**Comment by codepunkt** [comment]
We could have a CI environment variable, use that as ENV in yarn build and somehow read that from your plugin. Not sure where to continue from there. Just committing the files in a directory outside of node_modules and making this configurable seems so much easier.

**Comment by andrewbranch** [comment]
Update: I’m about to push a fix for this, but I’m going to backtrack on this:

> To clarify, I would copy only the files we actually need out of the plugin contents.

I’m not sure if the Visual Studio Marketplace requires that extensions have a certain license, but blowing away a bunch of files from someone else’s code could potentially put the user of this plugin in violation of the license agreement of an extension they were downloading. Even with MIT, you’re supposed to leave the license file and copyright info intact when redistributing, so if someone used a weird file extension on their license that led gatsby-remark-vscode to delete it, then you pushed that copy in your repo to GitHub or something, that’d be a license violation (IIUC IANAL etc.).

So, just to cover my own bases, I’m going to have it keep the whole extension intact, and if the user wanted to trim it down before checking it in, they can go for it.
