### ISSUE TITLE
Allow manual switch of dark/light mode

### ISSUE THREAD

**Issue by JCQuintas** [andrewbranch/gatsby-remark-vscode#39]
First I would like to say this is a great idea! :)

Now to the matter at hand, `prefers-color-scheme: dark` is all the hot fuss, but I would like to allow my users to override that if they want, so I have a **switch** to select the themes.

Is there an easy way to switch themes like that? Be it a `css` variable or a `className`?

**Comment by andrewbranch** [comment]
There are ways you can do it, like using [replaceColor](https://github.com/andrewbranch/gatsby-remark-vscode#tweaking-or-replacing-theme-colors), but I’m considering adding a one-liner config option to help with this.

**Comment by JCQuintas** [comment]
This option could be implemented like this:

```js
  colorTheme: {
    defaultTheme: 'Solarized Light',
    darkTheme: 'Monokai Dimmed',
    lightTheme: 'Quiet Light',
    detectionMethod: 'prefers-color-scheme' | 'classname/manual',
    classNames: {
      dark: 'gatsby-remark-vscode-dark',
      light: 'gatsby-remark-vscode-light',
    }
  }
```

So one could manually add `.gatsby-remark-vscode-dark` to the page/container and it would get picked by the `css`?

**Comment by andrewbranch** [comment]
More or less, except

1. you should be able to use _both_ prefer-scolor-scheme and a class name
2. I’d rather use a general CSS selector than a class name specifically.

**Comment by codepunkt** [comment]
I'm also looking into this.
