### ISSUE TITLE
Extensions not working (maybe)

### ISSUE THREAD

**Issue by Dajamante** [andrewbranch/gatsby-remark-vscode#44]
Hi!
I feel really rude to open an issue, I just have a question! The importation of extensions does not seem to work (for me): 

```js
  {
            resolve: `gatsby-remark-vscode`,
            ... some default options ...
              extensions: [
                {
                  identifier: "aaron-bond.better-comments",
                  version: "2.0.5",
                },
                {
                  identifier: "oderwat.indent-rainbow",
                  version: "7.4.0",
                },
              
              ]            
            ... some default options ...
          },
```

Is it something I am doing wrong?

**Comment by gagan0723** [comment]
I think you are using this as a standalone plugin which is wrong. Instead this plugin should be used with for example `gatsby-transformer-remark` [like so](https://github.com/andrewbranch/gatsby-remark-vscode#getting-started).

In case I am wrong please post your `gatsby-config.js` file's content.

**Comment by Dajamante** [comment]
Thank you very much for your reply ! ❤️ 
I use it in there:
```js
 extensions: [],         // Extensions to download from the marketplace to provide more languages and themes
```

Here is my config. Maybe it should be in another place?

```js
const path = require("path")

module.exports = {
  siteMetadata: {
    title: `Wrong Answer`,
    author: `me`,
    description: `A personal blog with programming puzzles`,
    siteUrl: `https://nifty-boxer-dog.netlify.com/`,
    social: {
      twitter: `bestcataccount`,
      facebook: `obertkollare`,
    },
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/assets`,
        name: `assets`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          {
            resolve: `gatsby-remark-vscode`,
            // All options are optional. Defaults shown here.
            options: {
              colorTheme: "Monokai", // Read on for list of included themes. Also accepts object and function forms.
              wrapperClassName: "pre", // Additional class put on 'pre' tag
              injectStyles: true, // Injects (minimal) additional CSS for layout and scrolling
              extensions: [
                {
                  identifier: "aaron-bond.better-comments",
                  version: "2.0.5",
                },
                {
                  identifier: "oderwat.indent-rainbow",
                  version: "7.4.0",
                },
              ], // Extensions to download from the marketplace to provide more languages and themes
              languageAliases: {}, // Map of custom/unknown language codes to standard/known language codes
              replaceColor: x => x, // Function allowing replacement of a theme color with another. Useful for replacing hex colors with CSS variables.
              getLineClassName: ({
                // Function allowing dynamic setting of additional class names on individual lines
                content, //   - the string content of the line
                index, //   - the zero-based index of the line within the code fence
                language, //   - the language specified for the code fence
                codeFenceOptions, //   - any options set on the code fence alongside the language (more on this later)
              }) => "",
              // Absolute path to the directory where extensions will be downloaded. Defaults to inside node_modules.
              extensionDataDirectory: path.resolve("extensions"),
              logLevel: "error", // Set to 'warn' to debug if something looks wrong
            },
          },
          {
            resolve: "gatsby-remark-emojis",
            options: {
              // Deactivate the plugin globally (default: true)
              active: true,
              // Add a custom css class
              class: "emoji-icon",
              // Select the size (available size: 16, 24, 32, 64)
              size: 64,
              // Add custom styles
              styles: {
                display: "inline",
                margin: "0",
                "margin-top": "1px",
                position: "relative",
                top: "5px",
                width: "25px",
              },
            },
          },
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        //trackingId: `ADD YOUR TRACKING ID HERE`,
      },
    },
    `gatsby-plugin-feed`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Gatsby Starter Blog`,
        short_name: `GatsbyJS`,
        start_url: `/`,
        background_color: `#ffffff`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `content/assets/gatsby-icon.png`,
      },
    },
    `gatsby-plugin-offline`,
    `gatsby-plugin-sitemap`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
  ],
}
//might use in the future `gatsby-plugin-google-fonts`
```

**Comment by gagan0723** [comment]
I am sorry I misunderstood your question. Your `gatsby-config` looks fine.
It may be the case that you get an error because of `rate limit`. If that's the case you need to wait until the server stops blocking download requests.

**Comment by Dajamante** [comment]
Is there anything I should do to limit the rate limit?

**Comment by gagan0723** [comment]
>Is there anything I should do to limit the rate limit?

There's nothing you can do about the limit rate because that's handled by the server.

Since most `VSCode` themes are open-source you can clone the repo and build it and copy the build over to `extensions` directory(in your case).

Here are the links to both the repo's: [better-comments](https://github.com/aaron-bond/better-comments) and [vscode-indent-rainbow](https://github.com/oderwat/vscode-indent-rainbow)

I think you can close this issue.

**Comment by andrewbranch** [comment]
> I feel really rude to open an issue, I just have a question!

Questions are welcome! 😄 

First, you should delete all the options you’re not using. It looks like you’ve copied and pasted all of them from the README.

> It may be the case that you get an error because of rate limit.

If rate limiting prevented the successful install of an extension, the build would fail. You haven’t told us what the symptoms of your problem are. Are builds failing, or are you just not seeing the syntax highlighting you expect?

**Comment by Dajamante** [comment]
Hi! ! Yes, the build works. But if it is expected behavior, is there a way to implement those options?

**Comment by andrewbranch** [comment]
This plugin isn’t interested in supporting extensions that aren’t themes. You could probably implement a similar effect yourself with the `getLineClassName` option.

**Comment by Dajamante** [comment]
Ok, I get it. Is it a way to make the language for the code snippets visible, on the top of the code? Like they do in Gatsby?

**Comment by andrewbranch** [comment]
Yep, I know @janosh has done that: https://janosh.io/blog/use-dark-mode

**Comment by Dajamante** [comment]
That's so neat! But how?

**Comment by janosh** [comment]
@Dajamante [Take a look here](https://github.com/janosh/janosh.io/blob/master/src/utils/syntaxHighlight.js#L25).

**Comment by Dajamante** [comment]
@janosh @andrewbranch you are two stars!

**Comment by Dajamante** [comment]
@janosh a last question: (I started react 2/3 weeks ago so it's a steeeeeep curve): where do I create global styles.js ? Maybe I only need to import const languageTags into the vscode options?

**Comment by janosh** [comment]
I'm using styled-components' [createGlobalStyle](https://www.styled-components.com/docs/api#createglobalstyle) API. This creates a React component [which I import in `Global.js`](https://github.com/janosh/janosh.io/blob/master/src/components/Global/index.js#L13) which is the layout component that functions as a template for all my site's pages. You don't need to adopt styled-components in particular if you're not familiar with it yet but some CSS-in-JS library is probably necessary if you want to adopt the way I'm adding these language tags.

**Comment by Dajamante** [comment]
First, thank you very much, I really appreciate that you take the time to explain! I have been trying to solve that for the whole time I was implementing the site.
So ideally I should be able to create a .css file for my template blog-post.js (since this is there I have the template for blog posts)? Would it work as a css in js?

**Comment by janosh** [comment]
> Would it work as a css in js?

Certainly, although you'd have a `.js` rather than a `.css` file in that case.

If you want to use bare-bones CSS you should probably take a look at how Gatsby implements these language tags. Last time I checked, they were using CSS only. I think [Lekoarts](https://www.lekoarts.de/en/blog/setting-up-a-gatsby-themes-workspace-with-typescript-eslint-and-cypress) is also using just CSS and the code for his site is probably easier to search than Gatsby's.

**Comment by Dajamante** [comment]
Sorry, I expressed myself wrongly. I mean: would it work as a .css _connected to_ a .js file, for example the template page for blog posts? Or shall I need to make a global .css file?
But I think you understood since you recommended Lekoarts's site. Looks like he is using TypeScript if I am not mistaken.
Also, shall I choose another mean of communication instead of flooding that thread which is closed (I don't know the protocols :)!)

**Comment by janosh** [comment]
> Also, shall I choose another mean of communication instead of flooding that thread which is closed (I don't know the protocols :)!)

Yes, I was going to mention that this is perhaps getting a little off-topic. But you can of course open an issue with questions against whichever repo you end up going with.

> But I think you understood since you recommended Lekoarts's site. Looks like he is using TypeScript if I am not mistaken.

Yes, he is writing much of his code in TypeScript these days although his portfolio site is still written in pure JavaScript. I was wrong about the CSS only though, [he's now using an approach that's more akin to mine](https://github.com/LekoArts/portfolio/blob/master/src/styles/prism.js#L23) and based on styled-components as well.

And here's [Gatsby's more verbose implementation](https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/www/src/utils/typography.js#L113) (also JS).

**Comment by LekoArts** [comment]
I got contacted by email and let the discussion to here, as it would be unrelated here: https://github.com/gatsbyjs/gatsby/issues/17439
