### ISSUE TITLE
Make line highlighting work without custom CSS

### ISSUE THREAD

**Issue by andrewbranch** [andrewbranch/gatsby-remark-vscode#51]
From the README:

> You need to pick your own background color, and optionally a left border width and color, for the highlighted lines. This can be done by setting CSS variables:

This is a bad default UX. We should be able to pick a reasonable highlight color from the theme text color. Dark themes are usually highlighted with ~10% opacity white; what are light themes usually highlighted with? 10% black is better than no default, but maybe we can pick one of the darker non-black syntax colors.

**Comment by andrewbranch** [comment]
I really want to change this, but it’s kind of a breaking change, so it’ll have to go in the next major version bump, and there are a few other things I want to lump in with that.

**Comment by zhenghaohe** [comment]
Hi I have been trying to add line highlighting to my code snippet. I copied what the doc is doing 
```js{1,3-5}
this.isLine(1) // highlighted
this.isLine(2)
this.isLine(3) // highlighted
this.isLine(4) // highlighted
this.isLine(5) // highlighted
```

but there is no highlighting. I wonder if it is because I didn't set any custom CSS? For example in the doc it says we can set the background color by adding this 
```
:root {
  --grvsc-line-highlighted-background-color: rgba(255, 255, 255, 0.2); /* default: transparent */
  --grvsc-line-highlighted-border-color: rgba(255, 255, 255, 0.5); /* default: transparent */
  --grvsc-line-highlighted-border-width: 2px; /* default: 4px */
}
```

But I don't know where exactly should I put it
