### ISSUE TITLE
Error: Cannot find module '../lib/grammars/manifest.json'

### ISSUE THREAD

**Issue by codepunkt** [andrewbranch/gatsby-remark-vscode#56]
Can't build my gatsby site anymore.

I'm not sure what happened or where this came from, but i don't have anything inside my node_modules/gatsby-remark-vscode/lib folder except a vscode folder, but neither grammars nor themes.

**Comment by andrewbranch** [comment]
Are you trying to install from your branch on GitHub? `npm publish` runs some build processes, so you can’t use the raw source without other steps.

**Comment by codepunkt** [comment]
Apparently, this happens when you have your own forked version installed via `yarn.lock` while you think you have the one from npm. My bad 👍
