### ISSUE TITLE
Way to load and cache extensions in CI builds?

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#61]
No idea how resource requests for VS Code extensions are authorized so this might be a dumb question. Is there an alternative to [committing extensions to VC](https://github.com/andrewbranch/gatsby-remark-vscode#dealing-with-rate-limiting-in-ci) in order to get CI builds to work? I'm getting something like this on Netlify.

```json
{
  "$id": "1",
  "innerException": null,
  "message": "Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).",
  "typeName": "Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server",
  "typeKey": "RequestBlockedException",
  "errorCode": 0,
  "eventId": 3000
}
```

This sounds like providing a proper value for `AnonymousId` as an environment variable might help.

**Comment by andrewbranch** [comment]
Honestly, I haven’t looked into this much. The URL in the message isn’t really helpful. One thing we could try is hitting `https://marketplace.visualstudio.com` first and saving the cookie returned in the response headers there, as it generates a session and user id. No guarantees this would increase any limits though.

**Comment by janosh** [comment]
I reached out to <vsmarketplace@microsoft.com> and asked how to avoid rate limits in CI builds. They were very helpful and got back to me with a few questions.

> Before we can suggest a solution to the problem we would like to understand the use case and details.
> Please help me understand the following details:
> 
> 1. What is “gatsby-remark-vscode” and how is it used?
> 2. What Marketplace APIs do you invoke and how do you make use of them?
> 3. What is the scale of your calls?
> 4. Would the traffic be in bursts or would it be consistent?
> 5. Is it possible for you to call the APIs as a logged in user?

I'm comfortable answering 1, 3 and 4 but was wondering about 2 (should I just point them at the [`downloadExtension` function](https://github.com/andrewbranch/gatsby-remark-vscode/blob/master/src/downloadExtension.js#L42)?) and what your thoughts are regarding 5 (as providing a way to setup credentials in GRV would mean people wanting to use that feature would need a Microsoft account).

Let me know if you want me to copy you in on the exchange.

**Comment by andrewbranch** [comment]
2. Yeah, just `https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${publisher}/vsextensions/${name}/${version}/vspackage`.
5. This isn’t viable in a CI scenario unfortunately.

Thanks for looking into this!

**Comment by janosh** [comment]
I'm afraid this has taken a turn to the unexpected. I got an email from the VS Marketplace team on Nov 27 saying GRV violates the marketplace terms of use and that they'd get in touch with you. They've since stopped replying to me. Very sorry about this...

> Hi Janosh,
>  
> Upon further inquiry into “gatsby-remark-vscode” and the scenario in which Marketplace extensions are used, we have identified that it violates the Marketplace terms of use listed here: https://aka.ms/vsmarketplace-ToU
> We will communicate with the repository owner regarding future steps.
>  
> Kind regards,
> Svetlana
> VS Marketplace team

**Comment by andrewbranch** [comment]
Yeah, I’ve been chatting with a VS Code PM about possible alternatives. At any rate, I don’t think there’s anything actionable for this issue.
