### ISSUE TITLE
Error on update to v2

### ISSUE THREAD

**Issue by Rodrigo54** [andrewbranch/gatsby-remark-vscode#68]
# **🐞 bug report**

I get a error on updated to version 2

![image](https://user-images.githubusercontent.com/8932920/71587270-cea06f00-2afb-11ea-81ea-e84449388826.png)

 i think `gatsby-remark-embed-gist` it clash this package in version 2

in version 1.4.0 it works

# 🔬 Minimal Reproduction

clone this repo
`git clone -b feature/gatsby --single-branch https://github.com/Rodrigo54/rodrigoalves.me.git`

and upgrade npm package gatsby-remark-vscode to alfa version
`npm install gatsby-remark-vscode@alpha`

# 🌍 My Environment
```
gatsby info

  System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  Binaries:
    Node: 12.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.10 => 2.3.10
    gatsby-plugin-styled-components: ^3.1.16 => 3.1.16
    gatsby-plugin-transition-link: ^1.17.7 => 1.17.7
    gatsby-plugin-typescript: ^2.1.23 => 2.1.23
    gatsby-remark-embed-gist: ^1.1.9 => 1.1.9
    gatsby-remark-images: ^3.1.39 => 3.1.39
    gatsby-remark-lazy-load: ^1.0.2 => 1.0.2
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-remark-vscode: ^2.0.0-alpha.20191227 => 2.0.0-alpha.20191227
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-transformer-remark: ^2.6.45 => 2.6.45
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7
```

**Comment by andrewbranch** [comment]
Thanks for trying the alpha! I’ll look into this before publishing the stable version 👍 

(ref: #64)

**Comment by andrewbranch** [comment]
I think this was likely the same issue reported by @janosh in #69. For some reason his has a stack trace attached, which made it easy to find the break. Should be fixed in the alpha that was just published.
